version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - telegram
    volumes:
      - redis_data:/funpayTg/data

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345tgv
      POSTGRES_DB: FunPayFollowBot
    networks:
      - telegram
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  telegram:

volumes:
  redis_data:
  postgres_data: